table Budget_Forecast
	lineageTag: a57f256d-64cf-44df-b11f-04563c8ac780

	column Type
		dataType: string
		lineageTag: 5b370fc4-e92d-416a-b84e-341fd8c10656
		summarizeBy: none
		sourceColumn: Type

		annotation SummarizationSetBy = Automatic

	column Year
		dataType: int64
		isHidden
		lineageTag: 9665ea9f-4651-4fae-9488-6a2d8d3191c8
		summarizeBy: none
		sourceColumn: Year

		annotation SummarizationSetBy = Automatic

	column Month
		dataType: string
		isHidden
		lineageTag: 7df34172-3105-4157-82b1-96176f8aa107
		summarizeBy: none
		sourceColumn: Month

		annotation SummarizationSetBy = Automatic

	column 'Month Number'
		dataType: int64
		isHidden
		lineageTag: c46a624f-b079-4002-a87d-5d3dcdf8aa47
		summarizeBy: none
		sourceColumn: MonthNo

		annotation SummarizationSetBy = Automatic

	column 'Month ID'
		dataType: int64
		isHidden
		lineageTag: 66eaa9f3-ce7a-4de6-94e6-d80f7ea6e5a0
		summarizeBy: none
		sourceColumn: MonthID

		annotation SummarizationSetBy = Automatic

	column Category
		dataType: string
		lineageTag: f9e71aca-0556-42fa-a375-e4b14875dfe6
		summarizeBy: none
		sourceColumn: Category

		annotation SummarizationSetBy = Automatic

	column Segment
		dataType: string
		lineageTag: 3c168859-b929-4fde-9508-d23469e5e61b
		summarizeBy: none
		sourceColumn: Segment

		annotation SummarizationSetBy = Automatic

	column Value
		dataType: double
		formatString: #,##0
		lineageTag: 936fb172-57e5-401a-8078-1bbbc62346e4
		summarizeBy: sum
		sourceColumn: Value

		annotation SummarizationSetBy = Automatic

	column BudgetDate = DATE ( Budget_Forecast[Year], Budget_Forecast[Month Number], 1 )
		dataType: dateTime
		isHidden
		formatString: dd mmm yyyy
		lineageTag: d3c4c467-9680-409a-acb5-81cbe5088439
		summarizeBy: none

		annotation SummarizationSetBy = Automatic

		annotation UnderlyingDateTimeDataType = Date

	partition Budget_Forecast = m
		mode: import
		source =
				let
				    Source = Csv.Document(File.Contents(DataFolder & "\Budget_Forecast.csv"), [Delimiter=",", Encoding=65001, QuoteStyle=QuoteStyle.Csv]),
				    Promoted = Table.PromoteHeaders(Source, [PromoteAllScalars=true]),
				    Typed = Table.TransformColumnTypes(Promoted, {
						{"Type", type text},
						{"Year", Int64.Type},
						{"Month", type text},
						{"MonthNo", Int64.Type},
						{"MonthID", Int64.Type},
						{"Category", type text},
						{"Segment", type text},
						{"Value", type number}
				    })
				in
				    Typed

	annotation PBI_ResultType = Table
