table Campaign
	lineageTag: 41225a2e-a4dc-4ea8-836e-72958519159a

	column CampaignID
		dataType: int64
		lineageTag: 4fea16eb-defa-4bf7-89c0-3abbb0cdd26d
		summarizeBy: none
		sourceColumn: CampaignID

		annotation SummarizationSetBy = Automatic

	column 'Traffic Channel'
		dataType: string
		lineageTag: 3d26f307-d4f3-4b66-a754-a05200a9c127
		summarizeBy: none
		sourceColumn: TrafficChannel

		annotation SummarizationSetBy = Automatic

	column Device
		dataType: string
		lineageTag: ef387762-553f-46f3-bf0f-23fb54e22d8b
		summarizeBy: none
		sourceColumn: Device

		annotation SummarizationSetBy = Automatic

	partition Campaign = m
		mode: import
		source =
				let
				    Source = Csv.Document(File.Contents(DataFolder & "\Campaign.csv"), [Delimiter=",", Encoding=65001, QuoteStyle=QuoteStyle.Csv]),
				    Promoted = Table.PromoteHeaders(Source, [PromoteAllScalars=true]),
				    Typed = Table.TransformColumnTypes(Promoted, {
						{"CampaignID", Int64.Type},
						{"TrafficChannel", type text},
						{"Device", type text}
				    })
				in
				    Typed

	annotation PBI_ResultType = Table
