table Customer
	lineageTag: 18d405b1-a1ef-4744-a6b5-3e55571452c8

	column CustomerID
		dataType: string
		isHidden
		lineageTag: 3431b265-acb8-4f74-9933-adca34ac0bec
		summarizeBy: none
		sourceColumn: CustomerID

		annotation SummarizationSetBy = Automatic

	column ZipCode
		dataType: string
		isHidden
		lineageTag: e6ad279f-9363-435c-a260-09aa13720913
		summarizeBy: none
		sourceColumn: ZipCode

		annotation SummarizationSetBy = Automatic

	column 'Email Name'
		dataType: string
		lineageTag: 26dbfac7-2827-4b7d-bf2d-8f3590c3336d
		summarizeBy: none
		sourceColumn: Email Name

		annotation SummarizationSetBy = Automatic

	partition Customer = m
		mode: import
		source =
				let
				    Source = Csv.Document(File.Contents(DataFolder & "\Customer.csv"), [Delimiter=",", Encoding=65001, QuoteStyle=QuoteStyle.Csv]),
				    Promoted = Table.PromoteHeaders(Source, [PromoteAllScalars=true]),
				    Typed = Table.TransformColumnTypes(Promoted, {
						{"CustomerID", type text},
						{"ZipCode", type text},
						{"Email Name", type text}
				    })
				in
				    Typed

	annotation PBI_ResultType = Table
