table Date
	lineageTag: 21609c9d-bf7f-4f0c-9a70-da91ba13451f
	dataCategory: Time

	column Date
		dataType: dateTime
		isKey
		formatString: dd mmm yyyy
		lineageTag: 24b81560-a45f-4819-b24a-bb8f76682361
		summarizeBy: none
		sourceColumn: Date

		annotation SummarizationSetBy = Automatic

		annotation UnderlyingDateTimeDataType = Date

	column Year
		dataType: int64
		lineageTag: fd1de4f6-cf46-4125-bd1f-3301a6ed9d4c
		summarizeBy: none
		sourceColumn: Year

		annotation SummarizationSetBy = Automatic

	column Quarter
		dataType: string
		lineageTag: f55e1059-df1d-4eb1-933d-14090a987e66
		summarizeBy: none
		sourceColumn: Quarter

		annotation SummarizationSetBy = Automatic

	column 'Year Quarter'
		dataType: string
		lineageTag: e569f44b-d4aa-44a0-af95-864c374e7a1f
		summarizeBy: none
		sourceColumn: YearQuarter

		annotation SummarizationSetBy = Automatic

	column Month
		dataType: string
		lineageTag: 1640c9fa-179e-47ef-bb69-51c32d375c3c
		summarizeBy: none
		sourceColumn: Month
		sortByColumn: 'Month ID'

		annotation SummarizationSetBy = Automatic

	column 'Month Name'
		dataType: string
		lineageTag: 898a3184-5bd2-42c6-92e6-961bf061d619
		summarizeBy: none
		sourceColumn: MonthName
		sortByColumn: 'Month Number'

		annotation SummarizationSetBy = Automatic

	column 'Month Number'
		dataType: int64
		isHidden
		lineageTag: a9ebae4c-9479-4f39-a8ea-855a72131dd4
		summarizeBy: none
		sourceColumn: MonthNo

		annotation SummarizationSetBy = Automatic

	column 'Month ID'
		dataType: int64
		isHidden
		lineageTag: 60e55de5-df52-4de1-8e1f-17c0b4d19894
		summarizeBy: none
		sourceColumn: MonthID

		annotation SummarizationSetBy = Automatic

	hierarchy 'Calendar Hierarchy'
		lineageTag: 45fdbf3c-9446-460c-9176-25f07b19d458

		level Year
			lineageTag: 9c875f00-e047-4918-ace4-aa3705d69134
			column: Year

		level Quarter
			lineageTag: 6b1ef018-cbfa-413e-8d7b-d4131f79fb69
			column: Quarter

		level Month
			lineageTag: efae133d-efa5-4976-87ad-58c062533261
			column: 'Month Name'

		level Date
			lineageTag: 1c1604e5-307f-4017-809c-d11cf71f4fc7
			column: Date

	partition Date = m
		mode: import
		source =
				let
				    Source = Csv.Document(File.Contents(DataFolder & "\Date.csv"), [Delimiter=",", Encoding=65001, QuoteStyle=QuoteStyle.Csv]),
				    Promoted = Table.PromoteHeaders(Source, [PromoteAllScalars=true]),
				    Typed = Table.TransformColumnTypes(Promoted, {
						{"Date", type date},
						{"Year", Int64.Type},
						{"Quarter", type text},
						{"YearQuarter", type text},
						{"Month", type text},
						{"MonthName", type text},
						{"MonthNo", Int64.Type},
						{"MonthID", Int64.Type}
				    })
				in
				    Typed

	annotation PBI_ResultType = Table
