table Geo
	lineageTag: 5fcd241b-2389-4246-a411-8ad9c801d2a9

	column Zip
		dataType: string
		isHidden
		lineageTag: f4c7f372-62ab-48d0-b85c-be6f12ae0ae8
		summarizeBy: none
		sourceColumn: Zip

		annotation SummarizationSetBy = Automatic

	column City
		dataType: string
		lineageTag: 9bfaaa59-bcf2-4427-a66f-9ec59993b627
		summarizeBy: none
		sourceColumn: City
		dataCategory: City

		annotation SummarizationSetBy = Automatic

	column State
		dataType: string
		lineageTag: c8ab30a6-9240-437a-a871-981b1b333460
		summarizeBy: none
		sourceColumn: State
		dataCategory: StateOrProvince

		annotation SummarizationSetBy = Automatic

	column Region
		dataType: string
		lineageTag: 4bc80e2f-1dd2-4beb-a055-4189ef36ca45
		summarizeBy: none
		sourceColumn: Region

		annotation SummarizationSetBy = Automatic

	column District
		dataType: string
		lineageTag: 233bb95d-aca6-4510-99eb-ea538059a214
		summarizeBy: none
		sourceColumn: District

		annotation SummarizationSetBy = Automatic

	column Country
		dataType: string
		lineageTag: b7ddb0bb-75dc-4f4e-9827-aded7fa069da
		summarizeBy: none
		sourceColumn: Country
		dataCategory: Country

		annotation SummarizationSetBy = Automatic

	partition Geo = m
		mode: import
		source =
				let
				    Source = Csv.Document(File.Contents(DataFolder & "\Geo.csv"), [Delimiter=",", Encoding=65001, QuoteStyle=QuoteStyle.Csv]),
				    Promoted = Table.PromoteHeaders(Source, [PromoteAllScalars=true]),
				    Typed = Table.TransformColumnTypes(Promoted, {
						{"Zip", type text},
						{"City", type text},
						{"State", type text},
						{"Region", type text},
						{"District", type text},
						{"Country", type text}
				    })
				in
				    Typed

	annotation PBI_ResultType = Table
