table 'Key Measures'
	lineageTag: b5320491-06bd-4290-9c06-aef5c8dfb6a9

	measure 'Units Sold' = SUM ( Sales[Units] )
		formatString: #,##0
		displayFolder: 01 Sales
		lineageTag: 4f1d2b75-2f37-419f-a6b1-83f78b64c641

	measure Revenue = SUMX ( Sales, Sales[Units] * RELATED ( Product[Unit Price] ) )
		formatString: #,##0
		displayFolder: 01 Sales
		lineageTag: 50c80efe-cb3f-484c-b51c-5f844d425591

	measure 'Average Selling Price' = DIVIDE ( [Revenue], [Units Sold] )
		formatString: #,##0.00
		displayFolder: 01 Sales
		lineageTag: dd5c4b28-1fe8-4ff7-af86-4c94870ca6b5

	measure 'Active Customers' = DISTINCTCOUNT ( Sales[CustomerID] )
		formatString: #,##0
		displayFolder: 01 Sales
		lineageTag: 794e2aff-eac4-43e9-b8cb-9fd3d7302c92

	measure COGS = SUMX ( Sales, Sales[Units] * RELATED ( Product[Unit Cost] ) )
		formatString: #,##0
		displayFolder: 02 Profitability
		isHidden
		lineageTag: 8cf975d6-0053-40b0-8f0f-ffe0d2a4b68a

	measure 'Gross Profit' = [Revenue] - [COGS]
		formatString: #,##0
		displayFolder: 02 Profitability
		lineageTag: dbabdad5-73f5-4b47-96ee-c20dfd72536c

	measure 'Gross Margin %' = DIVIDE ( [Gross Profit], [Revenue] )
		formatString: 0.0%
		displayFolder: 02 Profitability
		lineageTag: 9afbd5bb-efc5-446f-a48d-75fbdafc4926

	measure Budget = CALCULATE ( SUM ( Budget_Forecast[Value] ), Budget_Forecast[Type] = "Budget" )
		formatString: #,##0
		displayFolder: 03 Plan vs Actual
		lineageTag: dea692dc-d87a-4b64-8ef2-6e28d7d6c91e

	measure Forecast = CALCULATE ( SUM ( Budget_Forecast[Value] ), Budget_Forecast[Type] = "Forecast" )
		formatString: #,##0
		displayFolder: 03 Plan vs Actual
		lineageTag: d3d43f52-ae47-4a1e-9ba1-48c1695896be

	measure 'Budget Attainment %' = DIVIDE ( [Revenue], [Budget] )
		formatString: 0.0%
		displayFolder: 03 Plan vs Actual
		lineageTag: 0aeaf96e-a319-404f-bf8b-dd736241c8bd

	measure 'Forecast Variance' = [Revenue] - [Forecast]
		formatString: #,##0
		displayFolder: 03 Plan vs Actual
		lineageTag: 71bfc165-5563-4db7-8a40-08b7b608d724

	measure 'Forecast Variance %' = DIVIDE ( [Revenue] - [Forecast], [Forecast] )
		formatString: 0.0%
		displayFolder: 03 Plan vs Actual
		lineageTag: 1f730684-5e6a-43bf-90c3-9578f4e897ab

	measure 'Revenue PY' = CALCULATE ( [Revenue], DATEADD ( 'Date'[Date], -1, YEAR ) )
		formatString: #,##0
		displayFolder: 04 Time Intelligence
		lineageTag: b8fa1754-ae6b-4ff6-be39-5583d2db2771

	measure 'YoY Growth %' = DIVIDE ( [Revenue] - [Revenue PY], [Revenue PY] )
		formatString: 0.0%
		displayFolder: 04 Time Intelligence
		lineageTag: 0da78414-886b-4d5f-acc0-5517c4dc46f2

	partition 'Key Measures' = calculated
		mode: import
		source = {BLANK()}
