table Product
	lineageTag: 17bc4073-021a-4ced-811d-35da71d46ec5

	column ProductID
		dataType: int64
		isHidden
		lineageTag: 2b97d238-d3b2-42a1-9c1d-7f4d0029e7fe
		summarizeBy: none
		sourceColumn: ProductID

		annotation SummarizationSetBy = Automatic

	column Product
		dataType: string
		lineageTag: 8edd3fc2-1304-4665-8e1c-d63d52ba2f3b
		summarizeBy: none
		sourceColumn: Product

		annotation SummarizationSetBy = Automatic

	column Category
		dataType: string
		lineageTag: 8debce62-9b41-484a-82e2-ae8bcbe2bff5
		summarizeBy: none
		sourceColumn: Category

		annotation SummarizationSetBy = Automatic

	column Segment
		dataType: string
		lineageTag: 45af8970-614f-4cc3-9633-161c30b71f45
		summarizeBy: none
		sourceColumn: Segment

		annotation SummarizationSetBy = Automatic

	column Manufacturer
		dataType: string
		lineageTag: 4520a9fa-c69a-4695-afd1-4a1d8da7d81b
		summarizeBy: none
		sourceColumn: Manufacturer

		annotation SummarizationSetBy = Automatic

	column 'Unit Cost'
		dataType: double
		formatString: #,##0.00
		lineageTag: 44f6b472-349e-42e4-92c4-99fd64b68e39
		summarizeBy: none
		sourceColumn: Unit Cost

		annotation SummarizationSetBy = Automatic

	column 'Unit Price'
		dataType: double
		formatString: #,##0.00
		lineageTag: dcb58251-3278-4829-9206-6f0e3e3a54bc
		summarizeBy: none
		sourceColumn: Unit Price

		annotation SummarizationSetBy = Automatic

	partition Product = m
		mode: import
		source =
				let
				    Source = Csv.Document(File.Contents(DataFolder & "\Product.csv"), [Delimiter=",", Encoding=65001, QuoteStyle=QuoteStyle.Csv]),
				    Promoted = Table.PromoteHeaders(Source, [PromoteAllScalars=true]),
				    Typed = Table.TransformColumnTypes(Promoted, {
						{"ProductID", Int64.Type},
						{"Product", type text},
						{"Category", type text},
						{"Segment", type text},
						{"ManufacturerID", Int64.Type},
						{"Manufacturer", type text},
						{"Unit Cost", type number},
						{"Unit Price", type number}
				    })
				in
				    Typed

	annotation PBI_ResultType = Table
