table Sales
	lineageTag: c24db3ec-e3b7-4cf5-a949-fdd853d27c65

	column ProductID
		dataType: int64
		isHidden
		lineageTag: cd24199f-83fa-49ec-8ddf-0d974fb9b2e4
		summarizeBy: none
		sourceColumn: ProductID

		annotation SummarizationSetBy = Automatic

	column Date
		dataType: dateTime
		isHidden
		lineageTag: 51dd3f7c-f8a0-4a44-b6e1-73828a7509b1
		summarizeBy: none
		sourceColumn: Date

		annotation SummarizationSetBy = Automatic

		annotation UnderlyingDateTimeDataType = Date

	column CustomerID
		dataType: string
		isHidden
		lineageTag: b669e997-62f8-492e-9c6c-d312b4538018
		summarizeBy: none
		sourceColumn: CustomerID

		annotation SummarizationSetBy = Automatic

	column CampaignID
		dataType: int64
		isHidden
		lineageTag: 90272a19-3685-45c9-a3f4-f26df2c3f134
		summarizeBy: none
		sourceColumn: CampaignID

		annotation SummarizationSetBy = Automatic

	column Units
		dataType: int64
		formatString: #,##0
		lineageTag: 98038eef-c8d3-469c-aab9-cee5a9869ec8
		summarizeBy: sum
		sourceColumn: Units

		annotation SummarizationSetBy = Automatic

	partition Sales = m
		mode: import
		source =
				let
				    Source = Csv.Document(File.Contents(DataFolder & "\Sales.csv"), [Delimiter=",", Encoding=65001, QuoteStyle=QuoteStyle.Csv]),
				    Promoted = Table.PromoteHeaders(Source, [PromoteAllScalars=true]),
				    Typed = Table.TransformColumnTypes(Promoted, {
						{"ProductID", Int64.Type},
						{"Date", type date},
						{"CustomerID", type text},
						{"CampaignID", Int64.Type},
						{"Units", Int64.Type}
				    })
				in
				    Typed

	annotation PBI_ResultType = Table
