table Sales
	lineageTag: 1d5d937c-89af-411a-aaa8-38adb179cbf8

	column ProductID
		dataType: int64
		isHidden
		lineageTag: 326226a1-358f-422a-90e0-a6a2552ed320
		summarizeBy: none
		sourceColumn: ProductID

		annotation SummarizationSetBy = Automatic

	column Date
		dataType: dateTime
		isHidden
		lineageTag: d8a2ba67-d539-4a10-869b-8f85f9845d42
		summarizeBy: none
		sourceColumn: Date

		annotation SummarizationSetBy = Automatic

		annotation UnderlyingDateTimeDataType = Date

	column CustomerID
		dataType: string
		isHidden
		lineageTag: 7fe204a9-d415-4e7f-9036-f44eba8d42ae
		summarizeBy: none
		sourceColumn: CustomerID

		annotation SummarizationSetBy = Automatic

	column CampaignID
		dataType: int64
		isHidden
		lineageTag: 95c5fdb8-31da-4c0e-8650-f0529c598b35
		summarizeBy: none
		sourceColumn: CampaignID

		annotation SummarizationSetBy = Automatic

	column Units
		dataType: int64
		formatString: #,##0
		lineageTag: 21eaad34-49f8-4c09-bd87-90c04009deb3
		summarizeBy: sum
		sourceColumn: Units

		annotation SummarizationSetBy = Automatic

	partition Sales = m
		mode: import
		source =
				let
				    Source = Csv.Document(File.Contents(DataFolder & "\Sales.csv"), [Delimiter=",", Encoding=65001, QuoteStyle=QuoteStyle.Csv]),
				    Promoted = Table.PromoteHeaders(Source, [PromoteAllScalars=true]),
				    Typed = Table.TransformColumnTypes(Promoted, {
						{"ProductID", Int64.Type},
						{"Date", type date},
						{"CustomerID", type text},
						{"CampaignID", Int64.Type},
						{"Units", Int64.Type}
				    })
				in
				    Typed

	annotation PBI_ResultType = Table
